version: '3.4'

services:
  redis:
    image: redis:latest
    ports:
      - '6379:6379'

  cockroachdb:
    image: cockroachdb/cockroach:latest
    ports:
      - '26257:26257'
      - '8081:8080'
    volumes:
      - "${PWD}/cockroach-data/crdb:/cockroach/cockroach-data"
    command: start-single-node --insecure