//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

pub use super::customer::Entity as Customer;
pub use super::expense::Entity as Expense;
pub use super::regular_payment::Entity as RegularPayment;
