//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "ExpenseCategory")]
pub enum ExpenseCategory {
    #[sea_orm(string_value = "FOOD")]
    Food,
    #[sea_orm(string_value = "CLOTHES")]
    Clothes,
    #[sea_orm(string_value = "SUBSCRIPTIONS")]
    Subscriptions,
    #[sea_orm(string_value = "OTHER")]
    Other,
    #[sea_orm(string_value = "MEDICINE")]
    Medicine,
    #[sea_orm(string_value = "UTILITY_PAYMENTS")]
    UtilityPayments,
    #[sea_orm(string_value = "ANIMALS")]
    Animals,
    #[sea_orm(string_value = "PLACES_TO_EAT")]
    PlacesToEat,
    #[sea_orm(string_value = "EDUCATION")]
    Education,
    #[sea_orm(string_value = "BOOKS")]
    Books,
    #[sea_orm(string_value = "TAXI")]
    Taxi,
    #[sea_orm(string_value = "GIFTS")]
    Gifts,
    #[sea_orm(string_value = "DONATIONS")]
    Donations,
    #[sea_orm(string_value = "MOBILE_SERVICES")]
    MobileServices,
    #[sea_orm(string_value = "SPORTS")]
    Sports,
    #[sea_orm(string_value = "ENTERTAINMENT")]
    Entertainment,
    #[sea_orm(string_value = "BEAUTY_AND_CARE")]
    BeautyAndCare,
    #[sea_orm(string_value = "HOUSEHOLD")]
    Household,
    #[sea_orm(string_value = "PUBLIC_TRANSPORT")]
    PublicTransport,
    #[sea_orm(string_value = "TRAVEL")]
    Travel,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "Sex")]
pub enum Sex {
    #[sea_orm(string_value = "MALE")]
    Male,
    #[sea_orm(string_value = "FEMALE")]
    Female,
}
